language: node_js
cache: node_modules
node_js:
- '4.1'
#env:
#- CXX=g++-4.8
#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_1e36cf52d864_key -iv $encrypted_1e36cf52d864_iv
  -in .travis/id_rsa_travis_ci.enc -out ~/.ssh/id_rsa_travis_ci -d
- chmod 600 ~/.ssh/id_rsa_travis_ci
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_travis_ci
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "席铭"
- git config --global user.email "807754634@qq.com"
install:
- npm install hexo-cli -g
- npm install fs-extra --save
script:
- pwd
after_success:
- bash ./deploy/after.sh
branches:
  only:
  - master
